#!/usr/bin/env bash
# Sourced from your rc file (the block setup.sh adds). Loads the shared config, then the
# active profile's, then your own config.sh last so anything in it wins.

[[ -n "${ENVSETUP_ROOT:-}" ]] || return 0

_envsetup_state="$HOME/.config/envsetup"
ENVSETUP_PROFILE="" ENVSETUP_MODE=full
[[ -f "$_envsetup_state/profile" ]] && ENVSETUP_PROFILE="$(<"$_envsetup_state/profile")"
[[ "$ENVSETUP_PROFILE" == work && -f "$_envsetup_state/mode" ]] && ENVSETUP_MODE="$(<"$_envsetup_state/mode")"

# work lite assumes no sudo, so it only gets the prompt and aliases.
_envsetup_files=(ps1 aliases)
[[ "$ENVSETUP_MODE" == lite ]] || _envsetup_files+=(exports functions)
for _envsetup_f in "${_envsetup_files[@]}"; do
	# shellcheck disable=SC1090 # dynamic by design
	source "$ENVSETUP_ROOT/shell/shared/$_envsetup_f.sh"
done
# Exports for the dotfiles "Move dotfiles to XDG dirs" moved: every mode needs them, or
# the programs would recreate the files in $HOME.
# shellcheck source=/dev/null # generated by lib/xdg.sh
[[ -f "$_envsetup_state/xdg.sh" ]] && source "$_envsetup_state/xdg.sh"
if [[ -n "$ENVSETUP_PROFILE" ]]; then
	for _envsetup_f in "$ENVSETUP_ROOT/shell/profiles/$ENVSETUP_PROFILE"/*.sh; do
		# shellcheck disable=SC1090
		[[ -f "$_envsetup_f" ]] && source "$_envsetup_f"
	done
fi
# shellcheck source=/dev/null # user-supplied file
[[ -f "$_envsetup_state/config.sh" ]] && source "$_envsetup_state/config.sh"

unset _envsetup_state _envsetup_files _envsetup_f
