#!/usr/bin/env bash
# "Configure git": writes ENVSETUP_GIT_CONFIG (git/gitconfig + config.sh, later wins) to
# a generated file included from ~/.gitconfig, then asks for whatever identity is
# missing. Never needs sudo, so work lite gets it too.

ENVSETUP_GIT_GENERATED="$ENVSETUP_STATE/gitconfig"

envsetup::git_included() {
	git config --global --get-all include.path 2>/dev/null | grep -qxF "$ENVSETUP_GIT_GENERATED"
}

# For the dry run: true if <key> would still be unset after a real run, i.e. neither
# ENVSETUP_GIT_CONFIG nor anything ~/.gitconfig reaches sets it.
envsetup::git_unset() {
	local kv key
	for kv in "${ENVSETUP_GIT_CONFIG[@]}"; do
		key=${kv%%=*}
		[[ "${key,,}" == "${1,,}" ]] && return 1 # git keys are case-insensitive
	done
	[[ -z "$(git config --global --includes "$1" 2>/dev/null)" ]]
}

envsetup::configure_git() {
	local generated=$ENVSETUP_GIT_GENERATED kv key
	local -A hint=([name]='Your name' [email]='you@example.com')
	if envsetup::dry_run; then
		if envsetup::git_included; then
			envsetup::would "rewrite $generated (${#ENVSETUP_GIT_CONFIG[@]} git settings)"
		else
			envsetup::would "write ${#ENVSETUP_GIT_CONFIG[@]} git settings to $generated and include it from ~/.gitconfig"
		fi
		for key in name email; do
			if envsetup::git_unset "user.$key"; then envsetup::would "ask for your git user.$key"; fi
		done
		return 0
	fi

	# Rebuilt from scratch so entries removed from config.sh go away, via a temp file so
	# a bad entry leaves the last good version in place. --add keeps git's semantics:
	# last value wins, multi-valued keys accumulate.
	mkdir -p "${generated%/*}"
	echo "# Generated by envsetup from git/gitconfig + config.sh; edits here are overwritten." >"$generated.tmp"
	for kv in "${ENVSETUP_GIT_CONFIG[@]}"; do
		git config --file "$generated.tmp" --add "${kv%%=*}" "${kv#*=}"
	done
	mv "$generated.tmp" "$generated"
	if envsetup::git_included; then
		gum style --foreground 2 "Updated $generated"
	else
		git config --global --add include.path "$generated"
		gum style --foreground 2 "Included $generated in \$HOME/.gitconfig"
	fi

	# --includes: identity may come from config.sh via the generated file above.
	for key in name email; do
		[[ -n "$(git config --global --includes "user.$key" 2>/dev/null)" ]] ||
			git config --global "user.$key" "$(gum input --placeholder "${hint[$key]}")"
	done
}
